INSERT INTO player(name, email, phone, age, gender) VALUES ('Katherine Botsford', 'KatherineBotsford@sheridancollege.ca', '994 231-6043', 25, 'female');;
INSERT INTO player(name, email, phone, age, gender) VALUES ('Yvette Konopelski', 'YvetteKonopelski@sheridancollege.ca', '242 422-7914', 19, 'female');;
INSERT INTO player(name, email, phone, age, gender) VALUES ('Clyde Windler', 'ClydeWindler@sheridancollege.ca', '808-256-4708', 21, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Elsa Bernhard', 'ElsaBernhard@sheridancollege.ca', '910 755-1497', 42, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Yvonne Walsh', 'YvonneWalsh@sheridancollege.ca', '330-993-1125', 41, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Douglas Anderson', 'DouglasAnderson@sheridancollege.ca', '543 497-6635', 30, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Ella Williamson', 'EllaWilliamson@sheridancollege.ca', '706-966-8469', 24, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Jasmine Mayert', 'JasmineMayert@sheridancollege.ca', '1-476-353-6417', 35, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Melinda Streich', 'MelindaStreich@sheridancollege.ca', '296-245-4751', 49, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Lance Shields DVM', 'LanceShieldsDVM@sheridancollege.ca', '371-226-3464', 42, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Dwayne Schulist', 'DwayneSchulist@sheridancollege.ca', '898 840-9728', 42, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Eva Batz', 'EvaBatz@sheridancollege.ca', '725-242-6448', 19, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Constance Ledner', 'ConstanceLedner@sheridancollege.ca', '862-931-5257', 39, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Neil Beahan', 'NeilBeahan@sheridancollege.ca', '977 507-0047', 38, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Rosa Green', 'RosaGreen@sheridancollege.ca', '1-444-590-8371', 20, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Bennie Quitzon', 'BennieQuitzon@sheridancollege.ca', '260-859-2235', 35, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Diana Pollich', 'DianaPollich@sheridancollege.ca', '617-449-6543', 44, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Archie Pacocha', 'ArchiePacocha@sheridancollege.ca', '261-674-0981', 46, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Ebony Kerluke', 'EbonyKerluke@sheridancollege.ca', '887-971-8057', 37, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Sherman Simonis', 'ShermanSimonis@sheridancollege.ca', '1-782-365-7369', 33, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Woodrow Pacocha', 'WoodrowPacocha@sheridancollege.ca', '489-285-1255', 35, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Charlene Casper V', 'CharleneCasperV@sheridancollege.ca', '537 545-7437', 23, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Elaine Von', 'ElaineVon@sheridancollege.ca', '923-204-4034', 39, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Clifton Ward', 'CliftonWard@sheridancollege.ca', '466-564-3682', 29, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Frances Cummings', 'FrancesCummings@sheridancollege.ca', '1-775-231-0395', 49, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Kevin Mayert', 'KevinMayert@sheridancollege.ca', '1-288-809-5246', 19, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Katie Witting', 'KatieWitting@sheridancollege.ca', '204-441-2098', 32, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Nancy Kozey', 'NancyKozey@sheridancollege.ca', '404 927-6309', 34, 'female');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Craig Hayes', 'CraigHayes@sheridancollege.ca', '940 239-8551', 18, 'male');
INSERT INTO player(name, email, phone, age, gender) VALUES ('Micheal Rowe', 'MichealRowe@sheridancollege.ca', '897-556-6994', 38, 'male');

INSERT INTO team(name) VALUES('Sheridan Bruins');
INSERT INTO team(name) VALUES('Conestoga Condors');
INSERT INTO team(name) VALUES('Redeemer Royals');
INSERT INTO team(name) VALUES('Fanshawe Falcons');
INSERT INTO team(name) VALUES('Boreal Vipers');
INSERT INTO team(name) VALUES('Humber Hawks');
INSERT INTO team(name) VALUES('Mohawk Mountaineers');
INSERT INTO team(name) VALUES('St. Clair Saints');